# Generated by Django 4.0.5 on 2022-06-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('num_analysts', models.PositiveSmallIntegerField()),
                ('fwd_eps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fwd2_eps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fwd_rev', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fwd2_rev', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fwd_rev_g', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fwd2_rev_g', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
