# Generated by Django 4.0.5 on 2022-07-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe', '0002_estimate_capex1_estimate_capex2_estimate_capex3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='eps1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='eps2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='eps3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='eps4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
